name: Build Buku Kenangan APK

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Change wrapper permissions
      run: chmod +x ./gradlew

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 28
        build-tools: 28.0.3
        ndk: 23.1.7779620
        cmake: 3.18.1

    - name: Build Debug APK
      run: ./gradlew assembleDebug --no-daemon -x lint

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: apk-debug
        path: app/build/outputs/apk/debug/app-debug.apk